check:
  - thoth-build
release:
  - upload-pypi-sesheta
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.20.1
  build-stratergy: Source
  registry: quay.io
  registry-org: thoth-station
  registry-project: mi
  registry-secret: thoth-station-thoth-pusher-secret
deploy:
  project-org: thoth-station
  project-name: thoth-application
  image-name: mi
  overlay-contextpath: mi-scheduler/overlays/test/imagestreamtag.yaml
